name: "Configuración inicial de firewall"
label: "NETSEC"
description: "Onboarding de firewall (red, servicios, políticas base)"  
labels:  
  type: panos  
  os: panos 
  collection: 
    - PAN-OS

variables:  
  # Configuración de red  
  - name: fw_hostname  
    description: "Hostname del firewall"  
    type: text  
    default: "PA-Firewall"  

  - name: mgmt_ip  
    description: "IP/Máscara de gestión (ej: 192.168.1.1/24)"  
    type: text  
    default: "192.168.1.1/24"  

  # Servicios  
  - name: dns_servers  
    description: "Servidores DNS"  
    type: list  
    default: ["8.8.8.8", "8.8.4.4"]  

  # Políticas de seguridad  
  - name: mgmt_allowed_ips  
    description: "Redes permitidas para gestión (CIDR)"  
    type: text  
    default: "192.168.1.0/24"  

snippets:  
  - name: config_red  
    path: plantillas/network.xml.j2  
    targets:  
      - device-group  

  - name: config_servicios  
    path: plantillas/services.xml.j2  
    targets:  
      - device-group  

  - name: config_security_rules  
    path: plantillas/security_rules.xml.j2  
    targets:  
      - device-group  