name: App Filter Creator
label: App Filter Creator
description: >
  O365 Filter Creator

type: panos

labels:
  collection:
    - NetSec

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password

snippets:
  - name: filter_creator
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/application-filter
    file: app_filter.xml