name: Creacion_API_Key
# label used for menu selection
label: Generar PAN-OS API Key

description: |
  This skillet demonstrates a simple REST api call to a PAN-OS NGFW to generate a new API Key. This key will
  then be stored in your session for future use by other skillets that require the 'api_key' variable.

type: rest

labels:
  collection:
    - NETSEC

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key