name: Creacion_API_Key
label: Generar PAN-OS API Key

description: |
  Skillet para Generar la PAN-OS 'api_key'.

type: rest

labels:
  collection:
    - NETSEC

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password
    
snippets:
  - name: generate_api_key
    path: "https://{{ firewall_ip }}/api/?type=keygen&user={{ username }}&password={{ password }}"
    method: GET
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: "//key/text()"  # XPath directo al texto
        transform: "{{ output | trim }}"  # Elimina espacios/lineas extras

    # Validación de respuesta
    conditions:
      - name: valid_response
        xpath: "//@status = 'success'"
      - name: key_exists
        xpath: "boolean(//key)"