name: "generate_pan_api_key"
label: "Generate PAN-OS API Key"
description: "Generates API key for PAN-OS devices"
type: "rest"  # Tipo correcto para operaciones REST API


labels:
    collection:
      - NetSec

# Variables con validación
variables:
  - name: "target_ip"
    description: "Firewall management IP"
    type: "string"
    required: true
    hint: "IP or FQDN of the firewall"
  
  - name: "username"
    description: "Admin username"
    type: "string"
    required: true
    default: "admin"
  
  - name: "password"
    description: "Admin password"
    type: "password"
    required: true
    secret: true  # Marca como sensible

# Tareas REST (mejor que 'snippets' según doc)
tasks:
  - name: "generate_key"
    request:
      url: "https://{{ target_ip }}/api"
      method: "GET"
      params:
        type: "keygen"
        user: "{{ username }}"
        password: "{{ password }}"
      verify: false  # Para no verificar certificado SSL
    register: "api_response"  # Registra la respuesta
    failed_when: "api_response.status != 200 or 'result' not in api_response.json()"

# Procesamiento de salida
output:
  - name: "api_key"
    value: "{{ api_response.json().result.key }}"
    capture_pattern: "<key>(.*?)</key>"  # Patrón para extraer del XML
    description: "Generated API key"