name: Generate PAN-OS API Key
label: Generate PAN-OS API Key
description: |
  PAN-OS API KEY Generation

type: rest

labels:
  collection:
    - NetSec

variables:
  - name: TARGET_IP
    description: PAN-OS Device IP
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: Username 
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: paloalto
    type_hint: password

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen
    operation: post
    payload: user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    headers:
      Content-Type: application/x-www-form-urlencoded
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key