name: Creacion_API_Key_2.0
label: Generar PAN-OS API Key mediante Python

description: |
  Skillet para Generar la PAN-OS 'api_key'.

type: rest

labels:
  collection:
    - NETSEC

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password

snippets:
  - name: get_api_script
    file: get_api_script.py
    output_type: text
    outputs:
    - name: api_key