name: "PAN-OS API Key Generator Python"
description: "Generador API key Mediante Python"
type: python3
labels:
  collection: NETSEC
  os: python3
  sdk: true

variables:
  - name: target_ip
    description: "IP/FQDN del firewall"
    type: text
    required: true
  - name: username
    description: "Usuario administrativo"
    type: text
    default: "admin"
  - name: password
    description: "Contraseña"
    type: password
    required: true

outputs:
  - name: api_key
    description: "API Key generada"

entrypoint: generate_api_key.py