name: Creacion_API_Key_2.0
label: Generar PAN-OS API Key mediante Python

description: |
  Skillet para Generar la PAN-OS 'api_key'.

type: rest
labels:
  collection: NETSEC
  os: panos

variables:
  - name: TARGET_IP
    description: "IP/Host del firewall"
    default: "127.0.0.1"
    type_hint: fqdn_or_ip
    required: true

  - name: TARGET_USERNAME
    description: "Usuario administrativo"
    default: "admin"
    type_hint: text
    required: true

  - name: TARGET_PASSWORD
    description: "Contraseña"
    default: "admin"
    type_hint: password
    required: true

snippets:
  - name: generate_api_key
    script: get_api_script.py
    outputs:
      - name: api_key
        capture_pattern: "API_KEY=(.*)"