name: PAN-OS Security Rules
label: PAN-OS Init Security Rules

description: |
  Skillet para crear reglas de seguridad básicas en PAN-OS.

type: python3

labels:
  collection:
    - NetSec
    
variables:
  - name: TARGET_IP
    description: PAN-OS Device IP / Hostname
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: paloalto
    type_hint: password
  - name: FROM_ZONES
    description: "Zonas de origen (separadas por comas)"
    default: "trust"
    type_hint: text
  - name: TO_ZONES
    description: "Zonas de destino (separadas por comas)"
    default: "untrust"
    type_hint: text

snippets:
  - name: security_rules
    file: ../NetSec_InitConfig.py
    outputs:
      - name: config_status
        capture_pattern: "::set-output name=status::(.*)"